REST-56. Fix the startup scripts.
Changes the startup scripts to clean up how the root script and the "user"
script interact with each other. Now the root script delegates the
start/stop/status etc methods to the user script making the user script
execute all of this. Previously, the user level script was "mute" where it would
simply start the service overwriting logs but now it archives old logs and
accepts the start/stop etc.

Reviewer: lsheng, shashir, sebastian
commit: https://github.com/kijiproject/kiji-rest/commit/3beb489bdab3d196bb7da94c082240dbff8c8843

diff --git a/kiji-rest/kiji-rest/src/main/scripts/kiji-rest b/kiji-rest/kiji-rest/src/main/scripts/kiji-rest
--- a/kiji-rest/kiji-rest/src/main/scripts/kiji-rest
+++ b/kiji-rest/kiji-rest/src/main/scripts/kiji-rest
@@ -21,66 +21,175 @@
 
 cd $(dirname $0)/../
 BASEDIR=$PWD
+RETVAL=0
+SLEEP_TIME=5
 
-# attempt to find java (stolen from bigtop)
-if [ -z "$JAVA_HOME" ]; then
-  for candidate in \
-    /usr/lib/jvm/java-6-sun \
-    /usr/lib/jvm/java-1.6.0-sun-1.6.0.*/jre/ \
-    /usr/lib/jvm/java-1.6.0-sun-1.6.0.* \
-    /usr/lib/jvm/j2sdk1.6-oracle \
-    /usr/lib/jvm/j2sdk1.6-oracle/jre \
-    /usr/lib/j2sdk1.6-sun \
-    /usr/java/jdk1.6* \
-    /usr/java/jre1.6* \
-    /Library/Java/Home \
-    /usr/java/default \
-    /usr/lib/jvm/default-java \
-    /usr/lib/jvm/java-openjdk \
-    /usr/lib/jvm/jre-openjdk \
-    /usr/lib/jvm/java-1.6.0-openjdk-1.6.* \
-    /usr/lib/jvm/jre-1.6.0-openjdk* ; do
-    if [ -e $candidate/bin/java ]; then
-      export JAVA_HOME=$candidate
+# write logfiles to the /var/run/dir ... if run from initd
+logfile=${BASEDIR}/logs/console.out
+
+DESC="Kiji REST"
+
+initializeDirectories() {
+  # attempt to find java (stolen from bigtop)
+  if [ -z "$JAVA_HOME" ]; then
+    for candidate in \
+      /usr/lib/jvm/java-6-sun \
+      /usr/lib/jvm/java-1.6.0-sun-1.6.0.*/jre/ \
+      /usr/lib/jvm/java-1.6.0-sun-1.6.0.* \
+      /usr/lib/jvm/j2sdk1.6-oracle \
+      /usr/lib/jvm/j2sdk1.6-oracle/jre \
+      /usr/lib/j2sdk1.6-sun \
+      /usr/java/jdk1.6* \
+      /usr/java/jre1.6* \
+      /Library/Java/Home \
+      /usr/java/default \
+      /usr/lib/jvm/default-java \
+      /usr/lib/jvm/java-openjdk \
+      /usr/lib/jvm/jre-openjdk \
+      /usr/lib/jvm/java-1.6.0-openjdk-1.6.* \
+      /usr/lib/jvm/jre-1.6.0-openjdk* ; do
+      if [ -e $candidate/bin/java ]; then
+        export JAVA_HOME=$candidate
+        break
+      fi
+    done
+  fi
+
+  if [ -z "$JAVA_HOME" ]; then
+    echo "$JAVA_HOME not set."
+    exit 1
+  fi
+
+  if [ -z "$PIDFILE" ]; then
+    PIDFILE=${BASEDIR}/kiji-rest.pid
+  fi
+
+  kiji_rest_cp="${BASEDIR}/lib/*:${KIJI_CLASSPATH}"
+
+  if [ -z "${KIJI_REST_CONF_DIR}" ]; then
+    KIJI_REST_CONF_DIR=${BASEDIR}/conf
+  elif [ ! -d "${KIJI_REST_CONF_DIR}" ]; then
+    echo "KIJI_REST_CONF_DIR ($KIJI_REST_CONF_DIR) does not exist."
+    exit 1
+  fi
+
+  if [ -d "${KIJI_REST_CONF_DIR}" ]; then
+    kiji_rest_cp="${kiji_rest_cp}:${KIJI_REST_CONF_DIR}"
+  fi
+}
+
+function checkStatusOfProc(){
+  # Check that the process itself is there.
+  if [ -e ${PIDFILE} ]; then
+    PID=$(cat ${PIDFILE})
+    ps ${PID} > /dev/null 2>&1
+    if [ $? == 0 ]; then
+      echo "${DESC} is running. PID is ${PID}"
+    else
+      echo "${DESC} is not running."
+    fi
+    return 0
+  else
+    echo "${DESC} is not running."
+    return 1
+  fi
+}
+
+start() {
+  echo "Starting ${DESC}"
+
+  mkdir -p ${BASEDIR}/logs/archives
+
+  echo "Archiving old logs"
+  date=$(date +%Y%m%d%S)
+  for log_file in $(find ${BASEDIR}/logs -type f)
+  do
+    base_log=$(basename ${log_file})
+    mv ${log_file} ${BASEDIR}/logs/archives/${base_log}.${date}
+  done
+
+  ${JAVA_HOME}/bin/java -cp ${kiji_rest_cp} org.kiji.rest.KijiRESTService server \
+  ${BASEDIR}/conf/configuration.yml > ${logfile} 2>&1 &
+
+  echo $! > $PIDFILE
+
+  #Check that the server came up properly
+  for second in {0..30}
+  do
+    checkStatusOfProc
+    RETVAL=$?
+    if [ ${RETVAL} == 0 ]; then
       break
     fi
+    sleep 2
   done
-fi
 
-if [ -z "$JAVA_HOME" ]; then
-  echo "$JAVA_HOME not set."
-  exit 1
-fi
+  if [ -e ${PIDFILE} ]; then
+    echo PID saved to ${PIDFILE}
+  fi
 
-if [ -z "$PIDFILE" ]; then
-  PIDFILE=${BASEDIR}/kiji-rest.pid
-fi
+  return 0
+}
 
-kiji_rest_cp="${BASEDIR}/lib/*:${KIJI_CLASSPATH}"
 
-if [ -z "${KIJI_REST_CONF_DIR}" ]; then
-  KIJI_REST_CONF_DIR=${BASEDIR}/conf
-elif [ ! -d "${KIJI_REST_CONF_DIR}" ]; then
-  echo "KIJI_REST_CONF_DIR ($KIJI_REST_CONF_DIR) does not exist."
-  exit 1
-fi
+stop() {
+  echo "Stopping ${DESC}: "
 
-if [ -d "${KIJI_REST_CONF_DIR}" ]; then
-  kiji_rest_cp="${kiji_rest_cp}:${KIJI_REST_CONF_DIR}"
-fi
+  if [ ! -e ${PIDFILE} ]; then
+    echo "${PIDFILE} not found."
+    return 1
+  fi
 
-mkdir -p ${BASEDIR}/logs
-${JAVA_HOME}/bin/java -cp ${kiji_rest_cp} org.kiji.rest.KijiRESTService server \
-${BASEDIR}/conf/configuration.yml > ${BASEDIR}/logs/console.out 2>&1 &
+  pid=$(cat ${PIDFILE})
+  kill $pid
+  for second in {5..0}
+  do
+    retval=checkStatusOfProc
+    if [ ${retval} != 0 ] ; then
+      break
+    fi
+    sleep 2
+  done
 
-rest_server_pid=$!
+  if [ ${retval} == 0 ]; then
+    echo "Force killing ${DESC} PID = ${pid}"
+    kill -9 ${pid}
+  fi
+  rm -f ${PIDFILE}
+  return 0
+}
 
-# check if the backgrounded process truly started
-sleep 5
-ps -p ${rest_server_pid} > /dev/null
-if [ 0 == $? ]; then
-  echo ${rest_server_pid} > $PIDFILE
-else
-  exit 1
-fi
+checkstatus(){
+  checkStatusOfProc
+}
 
+restart() {
+  echo "About to restart ${DESC}"
+  stop
+  start
+}
+
+service() {
+  case "$1" in
+    start)
+      start
+      ;;
+    stop)
+      stop
+      ;;
+    status)
+      checkstatus
+      ;;
+    restart)
+      restart
+      ;;
+    *)
+      echo $"Usage: $0 {start|stop|status|restart}"
+      exit 1
+  esac
+}
+
+initializeDirectories
+service $1
+RETVAL=$?
+exit $RETVAL
diff --git a/kiji-rest/kiji-rest/src/main/scripts/kiji-rest.initd b/kiji-rest/kiji-rest/src/main/scripts/kiji-rest.initd
--- a/kiji-rest/kiji-rest/src/main/scripts/kiji-rest.initd
+++ b/kiji-rest/kiji-rest/src/main/scripts/kiji-rest.initd
@@ -39,6 +39,10 @@ KIJI_REST_HOME="/opt/wibi/kiji-rest"
 #Setup some directories
 mkdir -p ${RUNDIR}
 
+# ${LOCKDIR} is not a standard Linux directory, doesn't exist by default in ubuntu
+mkdir -p ${LOCKDIR}
+chown -R ${KIJI_REST_USER} ${RUNDIR}
+
 check_for_app() {
   if [ ! -e ${KIJI_REST_HOME} ]; then
     echo 'Kiji REST not installed!'
@@ -46,132 +50,72 @@ check_for_app() {
   fi
 }
 
-checkstatusofproc(){
-  # Check that the process itself is there.
-  if [ -e ${PIDFILE} ]; then
-    cat ${PIDFILE} | xargs ps -p > /dev/null
-  else
-    return 1
-  fi
-}
-
 start() {
+  execute_command "start"
+  retval=$?
 
-  echo "Starting ${DESC}: "
-  su -s /bin/bash -c "${KIJI_REST_HOME}/bin/kiji-rest" ${KIJI_REST_USER}
-
-  pidfile_orig=${KIJI_REST_HOME}/kiji-rest.pid
-  if [ -e ${pidfile_orig} ]; then
-    mv ${pidfile_orig} ${RUNDIR}
-  else
-    return 1
-  fi
-
-  #Check that the server came up properly.
-  for second in {30..0}
-  do
-    checkstatusofproc
-    RETVAL=$?
-    if [ ${RETVAL} == 0 ] ; then
-      break
-    fi
-    sleep 2
-  done
-
-  if [ ${RETVAL} != 0 ]; then
+  if [ ${retval} != 0 ]; then
     echo "${DESC} failed to start."
     rm -f ${PIDFILE}
   else
     touch $LOCKFILE
+    if [ $? != 0 ]; then
+      echo "Failed to create lockfile at location ${LOCKFILE}"
+    fi
   fi
 
   return $RETVAL
 }
 
 stop() {
-  echo "Stopping ${DESC}: "
-  if [ ! -e ${PIDFILE} ]; then
-    echo "${PIDFILE} not found."
-    return 1
-  fi
-
-  pid=$(cat ${PIDFILE})
-  kill $pid
-  for second in {5..0}
-  do
-    checkstatusofproc
-    RETVAL=$?
-    if [ $RETVAL != 0 ] ; then
-      break
-    fi
-    sleep 2
-  done
-
-  if [ ${RETVAL} == 0 ]; then
-    echo "Force killing ${DESC} PID = ${pid}"
-    kill -9 ${pid}
-  fi
-
-  rm -f $LOCKFILE $PIDFILE
-  return 0
+  execute_command "stop"
+  retval=$?
+  rm -f $LOCKFILE
+  return ${retval}
 }
 
 restart() {
-  stop
-  start
+  execute_command "restart"
   return $?
 }
 
 checkstatus(){
-  checkstatusofproc
-  status=$?
-  if [ $status == 0 ]; then
-    echo "${DESC} is running"
-  else
-    echo "${DESC} is not running."
-  fi
-
-  return $status
+  execute_command "status"
+  return $RETVAL
 }
 
-condrestart(){
-  [ -e $LOCKFILE ] && restart || :
+execute_command() {
+  command_name=$1
+  su -s /bin/bash -c "PIDFILE=${PIDFILE} ${KIJI_REST_HOME}/bin/kiji-rest ${command_name}" ${KIJI_REST_USER}
 }
 
 check_for_root() {
   if [ $(id -ur) -ne 0 ]; then
     echo 'Error: root user required'
-    echo
     exit 1
   fi
 }
 
 service() {
+  check_for_root
+  check_for_app
+
   case "$1" in
     start)
-      check_for_root
-      check_for_app
       start
       ;;
     stop)
-      check_for_root
-      check_for_app
       stop
       ;;
     status)
       checkstatus
       ;;
     restart)
-      check_for_root
-      check_for_app
       restart
       ;;
-    condrestart|try-restart)
-      check_for_root
-      condrestart
-      ;;
+
     *)
-      echo $"Usage: $0 {start|stop|status|restart|try-restart|condrestart}"
+      echo $"Usage: $0 {start|stop|status|restart}"
       exit 1
   esac
 }
