CHOP-54. Adds ability to run scripts with the chop script.
Use 'chop script' to run scripts and 'chop job' to run compiled jobs.

Reviewed by: kiyan
commit: https://github.com/kijiproject/kiji-express/commit/76a639df3a40ff43b1f0fd683d5e36e72047e59f

diff --git a/kiji-express/src/main/scripts/chop b/kiji-express/src/main/scripts/chop
--- a/kiji-express/src/main/scripts/chop
+++ b/kiji-express/src/main/scripts/chop
@@ -44,15 +44,15 @@ function resolve_symlink() {
   # Iterate down a (possible) chain of symlinks
   count=0
   while [ -L "$TARGET_FILE" ]; do
-      if [ "$count" -gt 1000 ]; then
-        # Just stop here, we've hit 1,000 recursive symlinks. (cycle?)
-        break
-      fi
+    if [ "$count" -gt 1000 ]; then
+      # Just stop here, we've hit 1,000 recursive symlinks. (cycle?)
+      break
+    fi
 
-      TARGET_FILE=$(readlink "$TARGET_FILE")
-      cd $(dirname "$TARGET_FILE")
-      TARGET_FILE=$(basename "$TARGET_FILE")
-      count=$(( $count + 1 ))
+    TARGET_FILE=$(readlink "$TARGET_FILE")
+    cd $(dirname "$TARGET_FILE")
+    TARGET_FILE=$(basename "$TARGET_FILE")
+    count=$(( $count + 1 ))
   done
 
   # Compute the canonicalized name by finding the physical path
@@ -78,7 +78,7 @@ CHOP_JAVA_OPTS=${CHOP_JAVA_OPTS:-""}
 # This is a workaround for OS X Lion, where a bug in JRE 1.6
 # creates a lot of 'SCDynamicStore' errors.
 if [ `uname` = "Darwin" ]; then
-    CHOP_JAVA_OPTS="$CHOP_JAVA_OPTS -Djava.security.krb5.realm= -Djava.security.krb5.kdc="
+  CHOP_JAVA_OPTS="$CHOP_JAVA_OPTS -Djava.security.krb5.realm= -Djava.security.krb5.kdc="
 fi
 
 # An existing set of directories to use for the java.library.path property should
@@ -91,22 +91,22 @@ HADOOP_HOME="${HADOOP_HOME:-/usr/lib/hadoop}"
 
 # First make sure we have everything we need in the environment.
 if [ -z ${CHOP_HOME} -o ! -d "${CHOP_HOME}" ]; then
-    echo "Please set your CHOP_HOME environment variable."
-    exit 1
+  echo "Please set your CHOP_HOME environment variable."
+  exit 1
 fi
 if [ -z ${HBASE_HOME} -o ! -d "${HBASE_HOME}" ]; then
-    echo "Please set your HBASE_HOME environment variable."
-    exit 1
+  echo "Please set your HBASE_HOME environment variable."
+  exit 1
 fi
 if [ -z ${HADOOP_HOME} -o ! -d "${HADOOP_HOME}" ]; then
-    echo "Please set your HADOOP_HOME environment variable."
-    exit 1
+  echo "Please set your HADOOP_HOME environment variable."
+  exit 1
 fi
 
 if [ -z $1 ]; then
-    echo "chop: Tool launcher for KijiChopsticks."
-    echo "Run 'chop help' to see a list of available tools."
-    exit 1
+  echo "chop: Tool launcher for KijiChopsticks."
+  echo "Run 'chop help' to see a list of available tools."
+  exit 1
 fi
 
 # Removes classpath entries that match the given regexp (partial match, not full
@@ -132,46 +132,42 @@ function append_path() {
 # if it finds the given jar.
 # mutate_classpath scrubme.jar "$(hadoop classpath)"
 function mutate_classpath () {
+  local mutated_classpath
+  local jar_to_scrub=$1
+  shift
 
-    local mutated_classpath
-    local jar_to_scrub=$1
-    shift
+  # Stop expanding globs
+  set -f
+  IFS=: read -r -a classpath <<< $@
 
-    # Stop expanding globs
-    set -f
-    IFS=: read -r -a classpath <<< $@
+  for path in $classpath; do
+    # If it ends with a glob we'll need to dig deeper for jars
+    if [ "${path: -1:1}" = "*" ]; then
+      set +f
+      local expanded_classpath=$(JARS=(${path}.jar); IFS=:; echo "${JARS[*]}")
+      set -f
 
-    for path in $classpath; do
+      # If the expanded classpath contains the jar in question, we'll
+      # scrub it later.
+      if [[ $expanded_classpath =~ .*$jar_to_scrub.* ]]; then
+        mutated_classpath=$(append_path $mutated_classpath $expanded_classpath)
 
-        # If it ends with a glob we'll need to dig deeper for jars
-        if [ "${path: -1:1}" = "*" ]; then
+      # If the expanded classpath doesn't contain the jar in question, use
+      # the glob version to reduce clutter.
+      else
+        mutated_classpath=$(append_path $mutated_classpath $path)
+      fi
+    # No glob just use the path
+    else
+      mutated_classpath=$(append_path $mutated_classpath $path)
+    fi
+  done
 
-            set +f
-            local expanded_classpath=$(JARS=(${path}.jar); IFS=:; echo "${JARS[*]}")
-            set -f
+  # Scrub all instances of the jar
+  mutated_classpath=$(remove_classpath_entries "$mutated_classpath" "$jar_to_scrub")
+  echo $mutated_classpath
 
-            # If the expanded classpath contains the jar in question, we'll
-            # scrub it later.
-            if [[ $expanded_classpath =~ .*$jar_to_scrub.* ]]; then
-                mutated_classpath=$(append_path $mutated_classpath $expanded_classpath)
-
-            # If the expanded classpath doesn't contain the jar in question, use
-            # the glob version to reduce clutter.
-            else
-                mutated_classpath=$(append_path $mutated_classpath $path)
-            fi
-
-        # No glob just use the path
-        else
-            mutated_classpath=$(append_path $mutated_classpath $path)
-        fi
-    done
-
-    # Scrub all instances of the jar
-    mutated_classpath=$(remove_classpath_entries "$mutated_classpath" "$jar_to_scrub")
-    echo $mutated_classpath
-
-    set +f
+  set +f
 }
 
 
@@ -201,30 +197,58 @@ if [ -d "${HADOOP_HOME}/lib/native" ]; then
   fi
 fi
 
+function jar_usage() {
+  echo "Usage: chop jar <jarFile> <mainClass> [args...]"
+  echo "       chop job <jarFile> <jobClass> [args...]"
+}
+
+function script_usage() {
+  echo "Usage: chop script <scriptFile> [args...]"
+}
+
 function jar_command() {
   if [[ $# > 0 && $1 == "--help" ]]; then
-    echo "Usage: chop <local|cluster|jar> <jarFile> <mainClass> [args...]"
+    jar_usage
     echo
     exit 0
   fi
-  user_jar_file=$1
+  user_target=$1
   class=$2
-  if [ -z "${user_jar_file}" ]; then
+  if [ -z "${user_target}" ]; then
     echo "Error: no jar file specified."
-    echo "Usage: chop <local|cluster|jar> <jarFile> <mainClass> [args...]"
+    jar_usage
     exit 1
   fi
-  if [ ! -f "${user_jar_file}" ]; then
-    echo "Error: Cannot find jar file ${user_jar_file}"
-    echo "Usage: chop <local|cluster|jar> <jarFile> <mainClass> [args...]"
+  if [ ! -f "${user_target}" ]; then
+    echo "Error: cannot find jar file ${user_target}"
+    jar_usage
     exit 1
   fi
   if [ -z "${class}" ]; then
     echo "Error: no main class specified."
-    echo "Usage: chop <local|cluster|jar> <jarFile> <mainClass> [args...]"
+    jar_usage
     exit 1
   fi
-  chop_cp="${user_jar_file}:${chop_cp}"
+  chop_cp="${user_target}:${chop_cp}"
+}
+
+function script_command() {
+  if [[ $# > 0 && $1 == "--help" ]]; then
+    script_usage
+    echo
+    exit 0
+  fi
+  user_target=$1
+  if [ -z "${user_target}" ]; then
+    echo "Error: no script file specified."
+    script_usage
+    exit 1
+  fi
+  if [ ! -f "${user_target}" ]; then
+    echo "Error: cannot find script file ${user_target}"
+    script_usage
+    exit 1
+  fi
 }
 
 function print_tool_usage() {
@@ -237,8 +261,8 @@ function print_tool_usage() {
   echo 'COMMANDS'
   echo
   echo '  help          - Displays this help message. Use --verbose for more information.'
-  echo '  local         - Runs an analysis job using the local job runner.'
-  echo '  hdfs          - Runs an analysis job using a Hadoop cluster.'
+  echo '  script        - Runs a raw chopsticks script.'
+  echo '  job           - Runs a compiled chopsticks job.'
   echo '  jar           - Runs an arbitrary Scala or Java program.'
   echo '  classpath     - Prints the classpath used to run KijiChopsticks.'
   echo
@@ -283,12 +307,26 @@ case ${command} in
     exit 0
     ;;
 
-  local|hdfs)
+  script)
     shift  # pop off the command
-    jar_command $@
+    script_command ${@}
+    shift
+    if [[ "${@}" != *--hdfs* ]] && [[ "${@}" != *--local* ]]; then
+      # Default run mode is local.
+      run_mode_flag="--local"
+    fi
+    scalding_tool="org.kiji.chopsticks.ScriptRunner"
+    ;;
+
+  job)
+    shift  # pop off the command
+    jar_command ${@}
     shift
     shift
-    run_mode=${command}
+    if [[ "${@}" != *--hdfs* ]] && [[ "${@}" != *--local* ]]; then
+      # Default run mode is local.
+      run_mode_flag="--local"
+    fi
     scalding_tool="com.twitter.scalding.Tool"
     ;;
 
@@ -298,14 +336,14 @@ case ${command} in
     shift
     shift
     ;;
-esac
 
-if [ -z "${class}" ]; then
+  *)
     echo "Unknown command: ${command}"
     echo "Try:"
     echo "  chop help"
     exit 1
-fi
+    ;;
+esac
 
 export CHOP_JAVA_OPTS
 
@@ -319,11 +357,17 @@ if [ -z "${scalding_tool}" ]; then
   exec java -cp "${chop_cp}" ${java_opts} ${CHOP_JAVA_OPTS} \
     "${class}" "$@"
 else
-  canonical_user_jar_file=$(readlink -e ${user_jar_file})
-  if [ -z "${canonical_user_jar_file}" ]; then
-    echo "Jar file does not exist: ${user_jar_file}"
+  canonical_user_target=$(readlink -e ${user_target})
+  if [ -z "${canonical_user_target}" ]; then
+    echo "File does not exist: ${user_target}"
     exit 1
   fi
-  exec java -cp "${chop_cp}" ${java_opts} ${CHOP_JAVA_OPTS} ${scalding_tool} \
-    "-Dtmpjars=file://${canonical_user_jar_file}" "${class}" "--${run_mode}" "$@"
+
+  if [ -z "${class}" ]; then
+    exec java -cp "${chop_cp}" ${java_opts} ${CHOP_JAVA_OPTS} ${scalding_tool} \
+      "${canonical_user_target}" "${run_mode_flag}" "$@"
+  else
+    exec java -cp "${chop_cp}" ${java_opts} ${CHOP_JAVA_OPTS} ${scalding_tool} \
+      "-Dtmpjars=file://${canonical_user_target}" "${class}" "${run_mode_flag}" "$@"
+  fi
 fi
